### ISSUE TITLE
Tutorial IrisClusteringNewAPI not working with the latest GenieFramework

### ISSUE THREAD

**Issue by svilupp** [GenieFramework/GenieFrameworkDemos_NewAPI#6] opened 2023-03-29 19:04 UTC
I've tried to run the Iris tutorial with the new API and simply instantiating packages as per Project.toml, but it fails.

How to reproduce? Simply instantiate based on Project.toml and run `dashboard.jl`.
If I use the provided Manifest.toml, it works but that's technically not for my system/platform.

Would it be possible to update the tutorial (I'm trying to read up on recent PRs) or set the appropriate compat entries in Project.toml?

On GenieFramework 1.13 (latest)
> WARNING: both Html and Base export "div"; uses of it in module Stipple must be qualified

> LoadError: BoundsError: attempt to access 1-element Vector{Any} at index [2]
> Stacktrace:
>   [1] getindex(A::Vector{Any}, i1::Int64)
>     @ Base ./array.jl:924
>   [2] var"@out"(__source__::LineNumberNode, __module__::Module, expr::Any)
>     @ Stipple.ReactiveTools ~/.julia/packages/Stipple/pgem3/src/ReactiveTools.jl:300

       
I know it has worked in the past, so I tried to downgrade, but there are still errors, eg, GenieFramework 1.5-1.10 gives

> LoadError: MethodError: no method matching on(::var"#33#34"{var"##Main_ReactiveModel!#314"}, ::typeof(vars))
> Closest candidates are:
>   on(::Any, ::AbstractObservable; weak, priority, update) at ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:356
>   on(::AbstractObservable, ::Function; weak) at ~/.julia/packages/Stipple/Ird4L/src/Stipple.jl:708
> Stacktrace:
>   [1] __GF_AUTO_HANDLERS__(__model__::var"##Main_ReactiveModel!#314")
>     @ Main ~/.julia/packages/Stipple/Ird4L/src/ReactiveTools.jl:643
>   [2] |>(x::var"##Main_ReactiveModel!#314", f::typeof(__GF_AUTO_HANDLERS__))
>     @ Base ./operators.jl:911
>   [3] top-level scope
>     @ ~/.julia/packages/Stipple/Ird4L/src/ReactiveTools.jl:422
>   [4] eval
>     @ ./boot.jl:368 [inlined]
>   [5] (::var"#35#36")()
>     @ Main ~/.julia/packages/Stipple/Ird4L/src/ReactiveTools.jl:711
>   [6] #invokelatest#2
>     @ ./essentials.jl:729 [inlined]
>   [7] invokelatest
>     @ ./essentials.jl:726 [inlined]
>   [8] Page(route::String; view::String, model::var"#35#36", layout::String, context::Module, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
>     @ Stipple.Pages ~/.julia/packages/Stipple/Ird4L/src/Pages.jl:56
>   [9] top-level scope
>     @ ~/.julia/packages/Stipple/Ird4L/src/ReactiveTools.jl:698

Associated Manifest.toml uses GenieFramework 1.0 which works.

My system:
> I've tried on many GenieFramework/Stipple versions, incl. the latest

> Julia Version 1.8.5
> Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
> Platform Info:
>   OS: macOS (arm64-apple-darwin21.5.0)
>   CPU: 8 × Apple M1 Pro
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
>   Threads: 6 on 6 virtual cores
> Environment:
>   JULIA_EDITOR = code
>   JULIA_NUM_THREADS = 8

**Comment by PGimenez** [comment] 2023-03-29 19:43
The issue is that `features`was not accessible from `cluster`. Fixed in [55423ff](https://github.com/GenieFramework/GenieFrameworkDemos_NewAPI/commit/55423ff40feddd0c8a275a5632785e690531d55a)

With the late updates to GF.jl, reactive variables tagged with @in @on can only be _read_ or _modified_ within an @onchange block.  For this particular example we just have to first define a regular `const features` so that that it can be accessed from `cluster`, and then define `@out features`inside the `@handlers`block.

**Closed as completed by PGimenez** 2023-03-29 19:43 UTC

**Comment by svilupp** [comment] 2023-03-30 08:45
Incredible! Thank you for the super fast response.

I've been playing with the new API, would it make sense to update the demo as well? I'm happy to open the PR:

```
using Clustering
import RDatasets: dataset
import DataFrames

using GenieFramework
@genietools

const data = DataFrames.insertcols!(dataset("datasets", "iris"), :Cluster => zeros(Int, 150))
function cluster(no_of_clusters=3, no_of_iterations=10; features)
    feats = Matrix(data[:, [c for c in features]])' |> collect
    result = kmeans(feats, no_of_clusters; maxiter=no_of_iterations)
    data[!, :Cluster] = assignments(result)
end

@app begin
    @in no_of_clusters = 3
    @in no_of_iterations = 10
    @in xfeature = :SepalLength
    @in yfeature = :SepalWidth
    @out features = [:SepalLength, :SepalWidth, :PetalLength, :PetalWidth]
    @out datatable = DataTable()
    @out datatablepagination = DataTablePagination(rows_per_page=50)
    @out irisplot = PlotData[]
    @out clusterplot = PlotData[]
    @out title = "My Iris Dashboard"

    @onchange isready, xfeature, yfeature, no_of_clusters, no_of_iterations begin
        cluster(no_of_clusters, no_of_iterations; features)
        datatable = DataTable(data)
        irisplot = plotdata(data, xfeature, yfeature; groupfeature=:Species)
        clusterplot = plotdata(data, xfeature, yfeature; groupfeature=:Cluster)
    end
end

@page("/", "ui.jl")

Server.isrunning() || Server.up()
```
You'll notice that I added features as a kwarg to avoid having to define it twice (not sure what would happen if they were defined inconsistently).

**Comment by PGimenez** [comment] 2023-03-31 15:12
@svilupp yes right, but seeing how features isn't optional, I think it should be a regular argument rather than a keyword. Feel free to submit the PR!
